/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as MarketerRouteRouteImport } from './routes/_marketer/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MarketerPortalRouteImport } from './routes/marketer-portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedSubjectsRouteImport } from './routes/_authenticated/subjects'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as LearnCourseIdRouteImport } from './routes/learn.$courseId'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryBookIdRouteImport } from './routes/library.$bookId'
import { Route as TeachersIndexRouteImport } from './routes/teachers.index'
import { Route as TeachersSlugRouteImport } from './routes/teachers.$slug'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminCoursesRouteImport } from './routes/_admin/admin.courses'
import { Route as AdminAdminLessonsRouteImport } from './routes/_admin/admin.lessons'
import { Route as AdminAdminLibraryRouteImport } from './routes/_admin/admin.library'
import { Route as AdminAdminMarketersRouteImport } from './routes/_admin/admin.marketers'
import { Route as AdminAdminOffersRouteImport } from './routes/_admin/admin.offers'
import { Route as AdminAdminQuizzesRouteImport } from './routes/_admin/admin.quizzes'
import { Route as AdminAdminStudentsRouteImport } from './routes/_admin/admin.students'
import { Route as AdminAdminTeachersRouteImport } from './routes/_admin/admin.teachers'
import { Route as AuthenticatedQuizQuizIdRouteImport } from './routes/_authenticated/quiz.$quizId'
import { Route as MarketerMarketerIndexRouteImport } from './routes/_marketer/marketer.index'
import { Route as MarketerMarketerDemoRouteImport } from './routes/_marketer/marketer.demo'
import { Route as MarketerMarketerEarningsRouteImport } from './routes/_marketer/marketer.earnings'
import { Route as MarketerMarketerLinksRouteImport } from './routes/_marketer/marketer.links'
import { Route as MarketerMarketerReportsRouteImport } from './routes/_marketer/marketer.reports'
import { Route as MarketerMarketerSettingsRouteImport } from './routes/_marketer/marketer.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketerRouteRoute = MarketerRouteRouteImport.update({
  id: '/_marketer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketerPortalRoute = MarketerPortalRouteImport.update({
  id: '/marketer-portal',
  path: '/marketer-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsRoute = AuthenticatedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryBookIdRoute = LibraryBookIdRouteImport.update({
  id: '/library/$bookId',
  path: '/library/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersSlugRoute = TeachersSlugRouteImport.update({
  id: '/teachers/$slug',
  path: '/teachers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminCoursesRoute = AdminAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminLessonsRoute = AdminAdminLessonsRouteImport.update({
  id: '/admin/lessons',
  path: '/admin/lessons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminLibraryRoute = AdminAdminLibraryRouteImport.update({
  id: '/admin/library',
  path: '/admin/library',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminMarketersRoute = AdminAdminMarketersRouteImport.update({
  id: '/admin/marketers',
  path: '/admin/marketers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminOffersRoute = AdminAdminOffersRouteImport.update({
  id: '/admin/offers',
  path: '/admin/offers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminQuizzesRoute = AdminAdminQuizzesRouteImport.update({
  id: '/admin/quizzes',
  path: '/admin/quizzes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminStudentsRoute = AdminAdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminTeachersRoute = AdminAdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedQuizQuizIdRoute = AuthenticatedQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MarketerMarketerIndexRoute = MarketerMarketerIndexRouteImport.update({
  id: '/marketer/',
  path: '/marketer/',
  getParentRoute: () => MarketerRouteRoute,
} as any)
const MarketerMarketerDemoRoute = MarketerMarketerDemoRouteImport.update({
  id: '/marketer/demo',
  path: '/marketer/demo',
  getParentRoute: () => MarketerRouteRoute,
} as any)
const MarketerMarketerEarningsRoute =
  MarketerMarketerEarningsRouteImport.update({
    id: '/marketer/earnings',
    path: '/marketer/earnings',
    getParentRoute: () => MarketerRouteRoute,
  } as any)
const MarketerMarketerLinksRoute = MarketerMarketerLinksRouteImport.update({
  id: '/marketer/links',
  path: '/marketer/links',
  getParentRoute: () => MarketerRouteRoute,
} as any)
const MarketerMarketerReportsRoute = MarketerMarketerReportsRouteImport.update({
  id: '/marketer/reports',
  path: '/marketer/reports',
  getParentRoute: () => MarketerRouteRoute,
} as any)
const MarketerMarketerSettingsRoute =
  MarketerMarketerSettingsRouteImport.update({
    id: '/marketer/settings',
    path: '/marketer/settings',
    getParentRoute: () => MarketerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/marketer-portal': typeof MarketerPortalRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/cart': typeof AuthenticatedCartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/library/$bookId': typeof LibraryBookIdRoute
  '/teachers/$slug': typeof TeachersSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/admin/courses': typeof AdminAdminCoursesRoute
  '/admin/lessons': typeof AdminAdminLessonsRoute
  '/admin/library': typeof AdminAdminLibraryRoute
  '/admin/marketers': typeof AdminAdminMarketersRoute
  '/admin/offers': typeof AdminAdminOffersRoute
  '/admin/quizzes': typeof AdminAdminQuizzesRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/admin/teachers': typeof AdminAdminTeachersRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/marketer/demo': typeof MarketerMarketerDemoRoute
  '/marketer/earnings': typeof MarketerMarketerEarningsRoute
  '/marketer/links': typeof MarketerMarketerLinksRoute
  '/marketer/reports': typeof MarketerMarketerReportsRoute
  '/marketer/settings': typeof MarketerMarketerSettingsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/marketer/': typeof MarketerMarketerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/marketer-portal': typeof MarketerPortalRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/cart': typeof AuthenticatedCartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/library/$bookId': typeof LibraryBookIdRoute
  '/teachers/$slug': typeof TeachersSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/library': typeof LibraryIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/admin/courses': typeof AdminAdminCoursesRoute
  '/admin/lessons': typeof AdminAdminLessonsRoute
  '/admin/library': typeof AdminAdminLibraryRoute
  '/admin/marketers': typeof AdminAdminMarketersRoute
  '/admin/offers': typeof AdminAdminOffersRoute
  '/admin/quizzes': typeof AdminAdminQuizzesRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/admin/teachers': typeof AdminAdminTeachersRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/marketer/demo': typeof MarketerMarketerDemoRoute
  '/marketer/earnings': typeof MarketerMarketerEarningsRoute
  '/marketer/links': typeof MarketerMarketerLinksRoute
  '/marketer/reports': typeof MarketerMarketerReportsRoute
  '/marketer/settings': typeof MarketerMarketerSettingsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/marketer': typeof MarketerMarketerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_marketer': typeof MarketerRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/marketer-portal': typeof MarketerPortalRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/vision': typeof VisionRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/subjects': typeof AuthenticatedSubjectsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/library/$bookId': typeof LibraryBookIdRoute
  '/teachers/$slug': typeof TeachersSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/_admin/admin/courses': typeof AdminAdminCoursesRoute
  '/_admin/admin/lessons': typeof AdminAdminLessonsRoute
  '/_admin/admin/library': typeof AdminAdminLibraryRoute
  '/_admin/admin/marketers': typeof AdminAdminMarketersRoute
  '/_admin/admin/offers': typeof AdminAdminOffersRoute
  '/_admin/admin/quizzes': typeof AdminAdminQuizzesRoute
  '/_admin/admin/students': typeof AdminAdminStudentsRoute
  '/_admin/admin/teachers': typeof AdminAdminTeachersRoute
  '/_authenticated/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/_marketer/marketer/demo': typeof MarketerMarketerDemoRoute
  '/_marketer/marketer/earnings': typeof MarketerMarketerEarningsRoute
  '/_marketer/marketer/links': typeof MarketerMarketerLinksRoute
  '/_marketer/marketer/reports': typeof MarketerMarketerReportsRoute
  '/_marketer/marketer/settings': typeof MarketerMarketerSettingsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_marketer/marketer/': typeof MarketerMarketerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/marketer-portal'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/vision'
    | '/cart'
    | '/dashboard'
    | '/profile'
    | '/records'
    | '/stats'
    | '/subjects'
    | '/wallet'
    | '/courses/$courseId'
    | '/learn/$courseId'
    | '/library/$bookId'
    | '/teachers/$slug'
    | '/courses/'
    | '/library/'
    | '/teachers/'
    | '/admin/courses'
    | '/admin/lessons'
    | '/admin/library'
    | '/admin/marketers'
    | '/admin/offers'
    | '/admin/quizzes'
    | '/admin/students'
    | '/admin/teachers'
    | '/quiz/$quizId'
    | '/marketer/demo'
    | '/marketer/earnings'
    | '/marketer/links'
    | '/marketer/reports'
    | '/marketer/settings'
    | '/admin/'
    | '/marketer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/marketer-portal'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/vision'
    | '/cart'
    | '/dashboard'
    | '/profile'
    | '/records'
    | '/stats'
    | '/subjects'
    | '/wallet'
    | '/courses/$courseId'
    | '/learn/$courseId'
    | '/library/$bookId'
    | '/teachers/$slug'
    | '/courses'
    | '/library'
    | '/teachers'
    | '/admin/courses'
    | '/admin/lessons'
    | '/admin/library'
    | '/admin/marketers'
    | '/admin/offers'
    | '/admin/quizzes'
    | '/admin/students'
    | '/admin/teachers'
    | '/quiz/$quizId'
    | '/marketer/demo'
    | '/marketer/earnings'
    | '/marketer/links'
    | '/marketer/reports'
    | '/marketer/settings'
    | '/admin'
    | '/marketer'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/_marketer'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/marketer-portal'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/vision'
    | '/_authenticated/cart'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/records'
    | '/_authenticated/stats'
    | '/_authenticated/subjects'
    | '/_authenticated/wallet'
    | '/courses/$courseId'
    | '/learn/$courseId'
    | '/library/$bookId'
    | '/teachers/$slug'
    | '/courses/'
    | '/library/'
    | '/teachers/'
    | '/_admin/admin/courses'
    | '/_admin/admin/lessons'
    | '/_admin/admin/library'
    | '/_admin/admin/marketers'
    | '/_admin/admin/offers'
    | '/_admin/admin/quizzes'
    | '/_admin/admin/students'
    | '/_admin/admin/teachers'
    | '/_authenticated/quiz/$quizId'
    | '/_marketer/marketer/demo'
    | '/_marketer/marketer/earnings'
    | '/_marketer/marketer/links'
    | '/_marketer/marketer/reports'
    | '/_marketer/marketer/settings'
    | '/_admin/admin/'
    | '/_marketer/marketer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MarketerRouteRoute: typeof MarketerRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MarketerPortalRoute: typeof MarketerPortalRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VisionRoute: typeof VisionRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  LearnCourseIdRoute: typeof LearnCourseIdRoute
  LibraryBookIdRoute: typeof LibraryBookIdRoute
  TeachersSlugRoute: typeof TeachersSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketer': {
      id: '/_marketer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketer-portal': {
      id: '/marketer-portal'
      path: '/marketer-portal'
      fullPath: '/marketer-portal'
      preLoaderRoute: typeof MarketerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$bookId': {
      id: '/library/$bookId'
      path: '/library/$bookId'
      fullPath: '/library/$bookId'
      preLoaderRoute: typeof LibraryBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$slug': {
      id: '/teachers/$slug'
      path: '/teachers/$slug'
      fullPath: '/teachers/$slug'
      preLoaderRoute: typeof TeachersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/courses': {
      id: '/_admin/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminAdminCoursesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/lessons': {
      id: '/_admin/admin/lessons'
      path: '/admin/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminAdminLessonsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/library': {
      id: '/_admin/admin/library'
      path: '/admin/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminAdminLibraryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/marketers': {
      id: '/_admin/admin/marketers'
      path: '/admin/marketers'
      fullPath: '/admin/marketers'
      preLoaderRoute: typeof AdminAdminMarketersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/offers': {
      id: '/_admin/admin/offers'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminAdminOffersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/quizzes': {
      id: '/_admin/admin/quizzes'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminAdminQuizzesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/students': {
      id: '/_admin/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminAdminStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/teachers': {
      id: '/_admin/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminAdminTeachersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/quiz/$quizId': {
      id: '/_authenticated/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_marketer/marketer/': {
      id: '/_marketer/marketer/'
      path: '/marketer'
      fullPath: '/marketer/'
      preLoaderRoute: typeof MarketerMarketerIndexRouteImport
      parentRoute: typeof MarketerRouteRoute
    }
    '/_marketer/marketer/demo': {
      id: '/_marketer/marketer/demo'
      path: '/marketer/demo'
      fullPath: '/marketer/demo'
      preLoaderRoute: typeof MarketerMarketerDemoRouteImport
      parentRoute: typeof MarketerRouteRoute
    }
    '/_marketer/marketer/earnings': {
      id: '/_marketer/marketer/earnings'
      path: '/marketer/earnings'
      fullPath: '/marketer/earnings'
      preLoaderRoute: typeof MarketerMarketerEarningsRouteImport
      parentRoute: typeof MarketerRouteRoute
    }
    '/_marketer/marketer/links': {
      id: '/_marketer/marketer/links'
      path: '/marketer/links'
      fullPath: '/marketer/links'
      preLoaderRoute: typeof MarketerMarketerLinksRouteImport
      parentRoute: typeof MarketerRouteRoute
    }
    '/_marketer/marketer/reports': {
      id: '/_marketer/marketer/reports'
      path: '/marketer/reports'
      fullPath: '/marketer/reports'
      preLoaderRoute: typeof MarketerMarketerReportsRouteImport
      parentRoute: typeof MarketerRouteRoute
    }
    '/_marketer/marketer/settings': {
      id: '/_marketer/marketer/settings'
      path: '/marketer/settings'
      fullPath: '/marketer/settings'
      preLoaderRoute: typeof MarketerMarketerSettingsRouteImport
      parentRoute: typeof MarketerRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminCoursesRoute: typeof AdminAdminCoursesRoute
  AdminAdminLessonsRoute: typeof AdminAdminLessonsRoute
  AdminAdminLibraryRoute: typeof AdminAdminLibraryRoute
  AdminAdminMarketersRoute: typeof AdminAdminMarketersRoute
  AdminAdminOffersRoute: typeof AdminAdminOffersRoute
  AdminAdminQuizzesRoute: typeof AdminAdminQuizzesRoute
  AdminAdminStudentsRoute: typeof AdminAdminStudentsRoute
  AdminAdminTeachersRoute: typeof AdminAdminTeachersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminCoursesRoute: AdminAdminCoursesRoute,
  AdminAdminLessonsRoute: AdminAdminLessonsRoute,
  AdminAdminLibraryRoute: AdminAdminLibraryRoute,
  AdminAdminMarketersRoute: AdminAdminMarketersRoute,
  AdminAdminOffersRoute: AdminAdminOffersRoute,
  AdminAdminQuizzesRoute: AdminAdminQuizzesRoute,
  AdminAdminStudentsRoute: AdminAdminStudentsRoute,
  AdminAdminTeachersRoute: AdminAdminTeachersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedSubjectsRoute: typeof AuthenticatedSubjectsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedQuizQuizIdRoute: typeof AuthenticatedQuizQuizIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedSubjectsRoute: AuthenticatedSubjectsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedQuizQuizIdRoute: AuthenticatedQuizQuizIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MarketerRouteRouteChildren {
  MarketerMarketerDemoRoute: typeof MarketerMarketerDemoRoute
  MarketerMarketerEarningsRoute: typeof MarketerMarketerEarningsRoute
  MarketerMarketerLinksRoute: typeof MarketerMarketerLinksRoute
  MarketerMarketerReportsRoute: typeof MarketerMarketerReportsRoute
  MarketerMarketerSettingsRoute: typeof MarketerMarketerSettingsRoute
  MarketerMarketerIndexRoute: typeof MarketerMarketerIndexRoute
}

const MarketerRouteRouteChildren: MarketerRouteRouteChildren = {
  MarketerMarketerDemoRoute: MarketerMarketerDemoRoute,
  MarketerMarketerEarningsRoute: MarketerMarketerEarningsRoute,
  MarketerMarketerLinksRoute: MarketerMarketerLinksRoute,
  MarketerMarketerReportsRoute: MarketerMarketerReportsRoute,
  MarketerMarketerSettingsRoute: MarketerMarketerSettingsRoute,
  MarketerMarketerIndexRoute: MarketerMarketerIndexRoute,
}

const MarketerRouteRouteWithChildren = MarketerRouteRoute._addFileChildren(
  MarketerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MarketerRouteRoute: MarketerRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MarketerPortalRoute: MarketerPortalRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VisionRoute: VisionRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  LearnCourseIdRoute: LearnCourseIdRoute,
  LibraryBookIdRoute: LibraryBookIdRoute,
  TeachersSlugRoute: TeachersSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
